---
title: "gather_leaflet"
author: "Nikita_Lledo"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(janitor)
library(rgdal)
library(tidyverse)
library(maptools)
```


```{r}

# Read in World Country code key. 

wb_codes <- read_csv("raw_data/wb_country_codes_2.csv",
                     col_types = cols(Continent_Name = col_character(),
                                      Continent_Code = col_character(),
                                      Country_Name = col_character(),
                                      Two_Letter_Country_Code = col_character(),
                                      Three_Letter_Country_Code = col_character(),
                                      Country_Number = col_double())) %>%
  clean_names() %>%
  mutate(country_code = three_letter_country_code)

# Read in World Bank population dataset. Left-join with WB country code key.

pop <- read_csv("raw_data/wb_pop2.csv",
                col_types = cols(.default = col_double(),
                                `Country Name` = col_character(),
                                `Country Code` = col_character(),
                                `Indicator Name` = col_character(),
                                `Indicator Code` = col_character(),
                                `2020` = col_logical())) %>%
  clean_names %>%
  select(country_code, x2013, x2018) %>%
  left_join(wb_codes, by = c("country_code" = "country_code"))


```

