---
title: "gather"
author: "Nikita_Lledo"
date: "10/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# loading the necessary libraries 

library(tidyverse)
library(readxl)
library(ggthemes)
library(leaflet)
library(tm)
library(gtsummary)
library(maptools)
library(janitor)
library(rstanarm)
library(gt)
library(wordcloud2)
library(infer)

library(sf)
library(ggplot2)
library(rgeos)
library(htmltools)
library(rgdal)
library(broom.mixed)

```


```{r}

# Reading and cleaning the 2018 data.
# We are adding a year column so that when we join the data we can 
# differentiate between data per year once data across years is joined. 
# I am joining two data sets, one from 2018 and one from 2013. I am renaming 
# variables to match between the two datasets as well as recoding the 2018 
# data to be numeric. 

d_2018 <- read.csv("raw_data/africabar_2018.csv") %>%
  mutate(year = "2018") %>%
  clean_names() %>%
  
# we are creating a country code using the first three letters of the respondent 
# ID. This is the same code between years. 
  
  mutate(country_code = toupper(str_sub(respno, 1, 3))) %>%
  
# Urban gives 2 if respondent is in a rural area, gives 1 if respondent is from
# a urban area. 
  
  rename(urban = urbrur) %>%
  mutate(urban = ifelse(urban == "Rural", 2, 1)) %>%
  
# gender returns 2 if female and 1 if respondent was male. 
  
  rename(gender = thisint) %>%
  mutate(gender = ifelse(gender == "Female", 2, 1)) %>%
  
# direction in which in respondent believes the country is going. this is a 
# binary variable that returns 2 if they believe the right direction, and 
# returns 1 if they believe the wrong direction. 
  
  rename(direction_country = q3) %>%
  mutate(direction_country = ifelse(direction_country == "Going in the right direction", 
                                    2, 1)) %>%
  
# current_eco is what the respondent believes the state of the current economy 
# to be. 
  
  rename(current_eco = q4a) %>%
  mutate(current_eco = case_when(current_eco == "Very good" ~ 5,
                                 current_eco == "Fairly Good" ~ 4,
                                 current_eco == "Neither good nor bad" ~ 3,
                                 current_eco == "Fairly Bad" ~ 2, 
                                 current_eco == "Very Bad" ~ 1,
                                 TRUE ~ 9)) %>%
  
# current_living is what the respondent believes the state of their current 
# living conditions to be. 
  
  rename(current_living = q4b) %>%
  mutate(current_living = case_when(current_living == "Very good" ~ 5,
                                    current_living == "Fairly Good" ~ 4,
                                    current_living == "Neither good nor bad" ~ 3,
                                    current_living == "Fairly Bad" ~ 2, 
                                    current_living == "Very Bad" ~ 1,
                                    TRUE ~ 9)) %>%
  
# comp_living is how the respondent believes their living standards compare to 
# that of others. 
  
  rename(comp_living = q5) %>%
  mutate(comp_living = case_when(comp_living == "Much better" ~ 5,
                                 comp_living == "Better" ~ 4,
                                 comp_living == "Same" ~ 3,
                                 comp_living == "Worse" ~ 2,
                                 comp_living == "Much worse" ~ 1,
                                 TRUE ~ 9)) %>%

# looking_back is what the respondent thinks of the economy currently compared 
# to 12 months ago. 
  
  rename(looking_back = q6) %>%
  mutate(looking_back = case_when(looking_back == "Much better" ~ 5,
                                  looking_back == "Better" ~ 4,
                                  looking_back == "Same" ~ 3,
                                  looking_back == "Worse" ~ 2,
                                  looking_back == "Much worse" ~ 1,
                                  TRUE ~ 9)) %>%
  
# looking_ahead is what the respondent thinks the economy will look like in 12
# months in comparison to the current economy. 
  
  rename(looking_ahead = q7) %>%
  mutate(looking_ahead = case_when(looking_ahead == "Much better" ~ 5,
                                   looking_ahead == "Better" ~ 4,
                                   looking_ahead == "Same" ~ 3,
                                   looking_ahead == "Worse" ~ 2,
                                   looking_ahead == "Much worse" ~ 1,
                                   TRUE ~ 9)) %>%
  
# pref_dem is the extent to which a respondent agrees with democracy. 
  
  rename(pref_dem = q28) %>%
  mutate(pref_dem = case_when(pref_dem == "STATEMENT 3: Doesn't matter" ~ 1,
                              pref_dem == "STATEMENT 2: Sometimes non-democratic preferable" ~ 2,
                              pref_dem == "STATEMENT 1: Democracy preferable" ~ 3,
                              TRUE ~ 9)) %>%
  
# extent_dem is the extent to which the respondent believes their country is 
# a democracy.
  
  rename(extent_dem = q35) %>%
  mutate(extent_dem = case_when(extent_dem == "A full democracy" ~ 4,
                                extent_dem == "A democracy, but with minor problems" ~ 3, 
                                extent_dem == "A democracy, with major problems" ~ 2, 
                                extent_dem == "Not a democracy" ~ 1,
                                extent_dem == "Do not understand question / democracy" ~ 8,
                                TRUE ~ 9)) %>%
  
# sat_dem is the extent to which a respondent is satisfied with democracy in 
# their country. 
  
  rename(sat_dem = q36) %>%
  mutate(sat_dem = case_when(sat_dem == "Very satisfied" ~ 4,
                             sat_dem == "Fairly satisfied" ~ 3,
                             sat_dem == "Not very satisfied" ~ 2,
                             sat_dem == "Not at all satisfied" ~ 1,
                             sat_dem == "The country is not a democracy" ~ 0,
                             TRUE ~ 9)) %>%
  
# unfair is how often the respondent believes that people are treated unfairly
# in their country. 
  
  rename(unfair = q42d) %>%
  mutate(unfair = case_when(unfair == "Always" ~ 3,
                            unfair == "Often" ~ 2,
                            unfair == "Rarely" ~ 1,
                            unfair == "Never" ~ 0,
                            TRUE ~ 9)) %>%
  
# import_prob1 is the problem that the respondent thought was most important 
# in their country. 
  
  rename(import_prob1 = q55pt1) %>%
  mutate(import_prob1 = case_when(import_prob1 == "Management of the economy" ~ 1,
                                  import_prob1 == "Wages, incomes and salaries" ~ 2,
                                  import_prob1 == "Unemployment" ~ 3, 
                                  import_prob1 == "Poverty/destitution" ~ 4,
                                  import_prob1 == "Rates and Taxes" ~ 5,
                                  import_prob1 == "Loans / credit" ~ 6,
                                  import_prob1 == "Farming/agriculture" ~ 7,
                                  import_prob1 == "Agricultural marketing" ~ 32,
                                  import_prob1 == "Food shortage/famine" ~ 8,
                                  import_prob1 == "Drought" ~ 9,
                                  import_prob1 == "Land" ~ 10,
                                  import_prob1 == "Transportation" ~ 11,
                                  import_prob1 == "Communications" ~ 12,
                                  import_prob1 == "Infrastructure / roads" ~ 13,
                                  import_prob1 == "Education" ~ 14,
                                  import_prob1 == "Housing" ~ 15,
                                  import_prob1 == "Electricity" ~ 16,
                                  import_prob1 == "Water supply" ~ 17,
                                  import_prob1 == "Orphans/street children/homeless children" ~ 18,
                                  import_prob1 == "Services (other)" ~ 19,
                                  import_prob1 == "Health" ~ 20,
                                  import_prob1 == "aids" ~ 21,
                                  import_prob1 == "Sickness / Disease" ~ 22,
                                  import_prob1 == "Crime and Security" ~ 23,
                                  import_prob1 == "Corruption" ~ 24,
                                  import_prob1 == "Political violence" ~ 25,
                                  import_prob1 == "Political instability / ethnic tensions" ~ 26,
                                  import_prob1 == "Discrimination/ inequality" ~ 27, 
                                  import_prob1 == "Gender issues / women’s rights" ~ 28,
                                  import_prob1 == "Democracy/political rights" ~ 29,
                                  import_prob1 == "Civil war" ~ 31,
                                  import_prob1 == "War (international)" ~ 30,
                                  TRUE ~ 9999)) %>%
  
# import_prob2 is the problem that the respondent thought was second most  
# important in their country. 
  
  rename(import_prob2 = q55pt2) %>%
  mutate(import_prob2 = case_when(import_prob2 == "Management of the economy" ~ 1,
                                  import_prob2 == "Wages, incomes and salaries" ~ 2,
                                  import_prob2 == "Unemployment" ~ 3, 
                                  import_prob2 == "Poverty/destitution" ~ 4,
                                  import_prob2 == "Rates and Taxes" ~ 5,
                                  import_prob2 == "Loans / credit" ~ 6,
                                  import_prob2 == "Farming/agriculture" ~ 7,
                                  import_prob2 == "Agricultural marketing" ~ 32,
                                  import_prob2 == "Food shortage/famine" ~ 8,
                                  import_prob2 == "Drought" ~ 9,
                                  import_prob2 == "Land" ~ 10,
                                  import_prob2 == "Transportation" ~ 11,
                                  import_prob2 == "Communications" ~ 12,
                                  import_prob2 == "Infrastructure / roads" ~ 13,
                                  import_prob2 == "Education" ~ 14,
                                  import_prob2 == "Housing" ~ 15,
                                  import_prob2 == "Electricity" ~ 16,
                                  import_prob2 == "Water supply" ~ 17,
                                  import_prob2 == "Orphans/street children/homeless children" ~ 18,
                                  import_prob2 == "Services (other)" ~ 19,
                                  import_prob2 == "Health" ~ 20,
                                  import_prob2 == "aids" ~ 21,
                                  import_prob2 == "Sickness / Disease" ~ 22,
                                  import_prob2 == "Crime and Security" ~ 23,
                                  import_prob2 == "Corruption" ~ 24,
                                  import_prob2 == "Political violence" ~ 25,
                                  import_prob2 == "Political instability / ethnic tensions" ~ 26,
                                  import_prob2 == "Discrimination/ inequality" ~ 27, 
                                  import_prob2 == "Gender issues / women’s rights" ~ 28,
                                  import_prob2 == "Democracy/political rights" ~ 29,
                                  import_prob2 == "Civil war" ~ 31,
                                  import_prob2 == "War (international)" ~ 30,
                                  TRUE ~ 9999)) %>%
  
# import_prob3 is the problem that the respondent thought was third most  
# important in their country.
           
  rename(import_prob3 = q55pt3) %>%
  mutate(import_prob3 = case_when(import_prob3 == "Management of the economy" ~ 1,
                                  import_prob3 == "Wages, incomes and salaries" ~ 2,
                                  import_prob3 == "Unemployment" ~ 3, 
                                  import_prob3 == "Poverty/destitution" ~ 4,
                                  import_prob3 == "Rates and Taxes" ~ 5,
                                  import_prob3 == "Loans / credit" ~ 6,
                                  import_prob3 == "Farming/agriculture" ~ 7,
                                  import_prob3 == "Agricultural marketing" ~ 32,
                                  import_prob3 == "Food shortage/famine" ~ 8,
                                  import_prob3 == "Drought" ~ 9,
                                  import_prob3 == "Land" ~ 10,
                                  import_prob3 == "Transportation" ~ 11,
                                  import_prob3 == "Communications" ~ 12,
                                  import_prob3 == "Infrastructure / roads" ~ 13,
                                  import_prob3 == "Education" ~ 14,
                                  import_prob3 == "Housing" ~ 15,
                                  import_prob3 == "Electricity" ~ 16,
                                  import_prob3 == "Water supply" ~ 17,
                                  import_prob3 == "Orphans/street children/homeless children" ~ 18,
                                  import_prob3 == "Services (other)" ~ 19,
                                  import_prob3 == "Health" ~ 20,
                                  import_prob3 == "aids" ~ 21,
                                  import_prob3 == "Sickness / Disease" ~ 22,
                                  import_prob3 == "Crime and Security" ~ 23,
                                  import_prob3 == "Corruption" ~ 24,
                                  import_prob3 == "Political violence" ~ 25,
                                  import_prob3 == "Political instability / ethnic tensions" ~ 26,
                                  import_prob3 == "Discrimination/ inequality" ~ 27, 
                                  import_prob3 == "Gender issues / women’s rights" ~ 28,
                                  import_prob3 == "Democracy/political rights" ~ 29,
                                  import_prob3 == "Civil war" ~ 31,
                                  import_prob3 == "War (international)" ~ 30,
                                  TRUE ~ 9999)) %>%
  
# election_fair is the extent to which a respondent thought the previous 
# election in there country was fair. 
           
  rename(election_fair = q23) %>%
  mutate(election_fair = case_when(election_fair == "Completely free and fair" ~ 4,
                                   election_fair == "Free and fair, but with minor problems" ~ 3,
                                   election_fair == "Free and fair, but with major problems" ~ 2,
                                   election_fair == "Not free and fair" ~ 1,
                                   election_fair == "Do not understand question" ~ 8,
                                   TRUE ~ 9)) %>%
  
# Selecting the relevant columns for the data analysis to later occur. 
  
  select(year, country_code, respno, urban, gender, direction_country, 
         current_eco,current_living, comp_living, looking_back, looking_ahead, 
         pref_dem, extent_dem, sat_dem, unfair, election_fair, import_prob1, 
         import_prob2, import_prob3)

```

```{r}

# reading in 2013 data. We follow the same naming convention for the variables
# in our 2018 dataset that we do in our 2013 dataset. 

d_2013 <- read.csv("raw_data/africabar_2013.csv") %>%
  mutate(year = "2013") %>%
  clean_names() %>%
  mutate(country_code = toupper(str_sub(respno, 1, 3))) %>%  
  rename(urban = urbrur) %>%
  rename(gender = thisint) %>%
  rename(current_eco = q3a) %>%
  rename(current_living = q3b) %>%
  rename(comp_living = q4) %>%
  rename(looking_back = q5a) %>%
  rename(looking_ahead = q6a) %>%
  rename(direction_country = q7) %>%
  rename(pref_dem = q32) %>%
  rename(extent_dem = q42) %>%
  rename(sat_dem = q43) %>%
  rename(unfair = q56b) %>%
  rename(election_fair = q28) %>%
  rename(import_prob1 = q63pt1) %>%
  rename(import_prob2 = q63pt2) %>%
  rename(import_prob3 = q63pt3) %>%
  
# selecting relevant columns to join with the 2018 dataset. 
  
  select(year, country_code, respno, urban, gender, direction_country, 
         current_eco,current_living, comp_living, looking_back, looking_ahead, 
         pref_dem, extent_dem, sat_dem, unfair, election_fair, import_prob1, 
         import_prob2, import_prob3)

```

```{r}

# Below we are joining the 2018 and 2013 datasets. 
# we rename the country codes to be in line with the world bank convention. 
# There was very little structure to how Afrobarometer did respondent country
# codes. therefore the renaming had to be done manually. 

joined_data <- bind_rows(d_2018, d_2013) %>%
  mutate(country_code = case_when(country_code == "ALG" ~ "DZA",
                                  country_code == "BFO" ~ "BFA",
                                  country_code == "BOT" ~ "BWA",
                                  country_code == "CAM" ~ "CMR",
                                  country_code == "CDI" ~ "CIV",
                                  country_code == "CVE" ~ "CPV",
                                  country_code == "GUI" ~ "GIN",
                                  country_code == "LES" ~ "LSO",
                                  country_code == "LIB" ~"LBR",
                                  country_code == "MAD" ~ "MDG",
                                  country_code == "MAU" ~ "MUS",
                                  country_code == "MLW" ~ "MWI",
                                  country_code == "NGR" ~ "NER",
                                  country_code == "GAM" ~ "GMB",
                                  country_code == "MOR" ~ "MAR",
                                  country_code == "NIG" ~ "NGA",
                                  country_code == "SAF" ~ "ZAF",
                                  country_code == "ZIM" ~ "ZWE",
                                  country_code == "ZAM" ~ "ZMB",
                                  country_code == "TOG" ~ "TGO",
                                  country_code == "TAN" ~ "TZA",
                                  country_code == "SUD" ~ "SDN",
                                  country_code == "SRL" ~ "SLE",
                                  country_code == "MRC" ~ "MAR",
                                  TRUE ~ country_code)) 

# the data used 9 as the code for a non response. Converting these to NA to 
# allow for easier data cleaning and dropping throughout analysis. 
  
joined_data$urban[joined_data$urban == 9] <- NA
joined_data$gender[joined_data$gender == 9] <- NA
joined_data$current_eco[joined_data$current_eco == 9] <- NA
joined_data$current_living[joined_data$current_living == 9] <- NA
joined_data$comp_living[joined_data$comp_living == 9] <- NA
joined_data$looking_back[joined_data$looking_back == 9] <- NA
joined_data$looking_ahead[joined_data$looking_ahead == 9] <- NA
joined_data$direction_country[joined_data$direction_country == 9] <- NA
joined_data$pref_dem[joined_data$pref_dem == 9] <- NA
joined_data$extent_dem[joined_data$extent_dem == 9] <- NA
joined_data$sat_dem[joined_data$sat_dem == 9] <- NA
joined_data$unfair[joined_data$unfair == 9] <- NA

# Saving the rds to be used as a dataset for my shiny app. 

saveRDS(joined_data, file = "shiny/data/joined_data.rds")

```

```{r}

# creating a list of the countries that I will be working with. 

list_countries <- unique(joined_data$country_code) %>%
  as_tibble() %>%
  rename(country_code = value)

```

```{r}

# The below code chuck focuses on getting world bank data for the countries 
# relevant for my analysis. 

# Here I am reading in the world bank data on codes, continents, and countries.
# specifically from here we are getting the formal name of each country. 

wb_codes <- read_csv("raw_data/wb_country_codes_2.csv",
                     col_types = cols(Continent_Name = col_character(),
                                      Continent_Code = col_character(),
                                      Country_Name = col_character(),
                                      Two_Letter_Country_Code = col_character(),
                                      Three_Letter_Country_Code = col_character(),
                                      Country_Number = col_double())) %>%
  clean_names() %>%
  mutate(country_code = three_letter_country_code) %>%
  filter(continent_name == "Africa") %>%
  select(continent_name, continent_code, country_name, country_code) 

# Read in World Bank population dataset. We pivot the data in order to join in
# at the end of the chuck with other relevant data. 

wb_pop <- read_csv("raw_data/wb_pop2.csv",
                col_types = cols(.default = col_double(),
                                `Country Name` = col_character(),
                                `Country Code` = col_character(),
                                `Indicator Name` = col_character(),
                                `Indicator Code` = col_character(),
                                `2020` = col_logical())) %>%
  clean_names %>%
  select(country_code, x2013, x2018) %>%
  pivot_longer(names_to = "year",
               values_to = "population",
               cols = c(x2013, x2018)) %>%
  mutate(year = str_replace(year, "x", ""))

# reading in world bank gdp data. We pivot the data in order to join in
# at the end of the chuck with other relevant data. 

wb_gdp <- read_csv("raw_data/wb_gdp2.csv",
                   col_types = cols(.default = col_double(),
                                    `Country Name` = col_character(),
                                    `Country Code` = col_character(),
                                    `Indicator Name` = col_character(),
                                    `Indicator Code` = col_character(),
                                    `2020` = col_logical())) %>%
  clean_names %>%
  select(country_code, x2013, x2018) %>%
  pivot_longer(names_to = "year",
               values_to = "gdp",
               cols = c(x2013, x2018)) %>%
  mutate(year = str_replace(year, "x", ""))

# joining sequence to join the data from the world bank. then joining the data 
# to list countries dataset to only get the relevant countries for this 
# project. 
  
wb_data <- left_join(wb_pop, wb_gdp, by = c("country_code", "year"))
wb_data_2 <- left_join(wb_codes, wb_data, by = "country_code")
wb_joined <- left_join(list_countries, wb_data_2, by = "country_code")

```

```{r}

# The below code chuck focuses on setting the data up to create an interactive 
# map. We are joining the data from the joined_data data set as well as the 
# world bank information in order to have data for our interactive map relating
# to population, GDP, formal country name, and average direction. 

data(wrld_simpl) 

world <- wrld_simpl 

direction_map_data <- joined_data %>%
  group_by(country_code, year) %>%
  drop_na() %>%
  mutate(direction_tot = sum(direction_country)/n() - 1) %>%
  select(country_code, direction_tot, year) %>%
  unique() %>%
  left_join(wb_joined, by = c("country_code", "year")) %>%
  filter(year == "2018")
  
world@data <- wrld_simpl@data %>%
  left_join(direction_map_data, by = c("ISO3" = "country_code"))
  
# Here we are setting the colors for the scale fill of the leaflet.
  
pal <- colorNumeric(palette = "Blues",
                    domain = world$direction_tot)

# We are saving the rds to use then in the server

saveRDS(world, file = "shiny/data/world.rds")

```

```{r}

# Below we are preparing the data to make bar graphs to show percent of 
# respondents who believe the country is going in the wrong direction versus 
# going in the right direction. This is for each country.

direction <- joined_data %>%
  group_by(country_code, year) %>%
  drop_na(direction_country) %>%
  mutate(num_resp = n()) %>%
  mutate(wrong = sum(direction_country == 1)/num_resp * 100) %>%
  mutate(right = sum(direction_country == 2)/num_resp * 100) %>%
  select(country_code, year, wrong, right, num_resp) %>%
  unique() %>%
  pivot_longer(names_to = "direction",
               values_to = "direction_value",
               cols = c(wrong, right)) %>%
  mutate(direction_value = ifelse(direction == "right",
                                  direction_value,
                                  -1*direction_value)) 

saveRDS(direction, file = "shiny/data/direction.rds")

# Below we are preparing data to create plots for a year 2018 vs year 2013 
# comparison of the direction in which all africans think their respective 
# country is going. 

direction_year_data <- direction %>%
  group_by(direction, year) %>%
  mutate(dirc_tot = sum(direction_value)/n()) %>%
  select(year, dirc_tot, direction) %>%
  unique() 

# we are saving this rds to use to create a graph in our server. 

saveRDS(direction_year_data, file = "shiny/data/direction_year_data.rds")

```

```{r}

# Here we are preparing the data to run regression models. We are changing 
# direction_country to still be a binary variable but on the scale of 1 and 0,
# whereby 1 is the right direction and 0 is the wrong direction. 

joined_data_stan <- joined_data %>%
  mutate(direction_country = ifelse(direction_country == 2, 1, 0)) 

saveRDS(joined_data_stan, file = "shiny/data/joined_data_stan.rds")

# Here we are running a binomial regression whereby we are modeling 
# direction_country as a function of numerous living and economic sentiments
# the the year of 2018 for all countries.

dirc_2018 <- stan_glm(formula = direction_country ~ current_eco + looking_back 
                      + looking_ahead + urban + current_living + comp_living, 
                      family = binomial,
                      data = joined_data_stan %>% filter(year == 2018),
                      refresh = 0)

# we are creating and saving the table for the regression for 2018. We are 
# saving the tables in the rmd to reduce the loading time of the shiny app.

tbl_2018 <- tbl_regression(dirc_2018) %>%
  as_gt() %>%
  tab_header(title = "Regression of belief of the Direction in 
             which the country is going 2018",
             subtitle= "The Effect of different variables on Direction") %>%
  tab_source_note("Afrobarometer") 

saveRDS(tbl_2018, file = "shiny/data/tbl_2018.rds")

# Here we are running a binomial regression whereby we are modeling 
# direction_country as a function of numerous living and economic sentiments
# the the year of 2013 for all countries.

dirc_2013 <- stan_glm(formula = direction_country ~ current_eco + looking_back 
                      + looking_ahead + urban + current_living + comp_living, 
                      family = binomial,
                      data = joined_data_stan %>% filter(year == 2013),
                      refresh = 0)

# we are creating and saving the table for the regression for 2013. 

tbl_2013 <- tbl_regression(dirc_2013) %>%
  as_gt() %>%
  tab_header(title = "Regression of belief of the Direction in 
             which the country is going 2013",
             subtitle= "The Effect of different variables on Direction") %>%
  tab_source_note("Afrobarometer") 

saveRDS(tbl_2013, file = "shiny/data/tbl_2013.rds")

```

```{r}

# Below we are preparing the data in order to create a wordcloud of what 
# people thought about the issues that face the country. More importantly 
# we are looking at how many people said a specific issue was in the three
# most important issues facing their country specifically. We aggregate this 
# for the data across the continent. 

sentiment1 <- joined_data %>%
  filter(import_prob1 %in% c(1:32)) %>%
  group_by(import_prob1, year) %>%
  summarize(countprob1 = n(),
            .groups = "drop") %>%
  rename(import_prob = import_prob1)

sentiment2 <- joined_data %>%
  filter(import_prob1 %in% c(1:32)) %>%
  group_by(import_prob2, year) %>%
  summarize(countprob2 = n(),
            .groups = "drop") %>%
  rename(import_prob = import_prob2)

sentiment3 <- joined_data %>%
  filter(import_prob1 %in% c(1:32)) %>%
  group_by(import_prob3, year) %>%
  summarize(countprob3 = n(),
            .groups = "drop") %>%
  rename(import_prob = import_prob3)


sent_tot <- sentiment1 %>%
  inner_join(sentiment2, by = c("import_prob", "year")) %>%
  inner_join(sentiment3, by = c("import_prob", "year")) %>%
  pivot_longer(names_to = "type",
               values_to = "number",
               cols = c(countprob1, countprob2, countprob3)) %>%
  group_by(import_prob, year) %>%
  mutate(total = sum(number),
         .groups = "drop") %>%
  select(import_prob, year, total) %>%
  unique() %>%
  mutate(import_prob = case_when(import_prob == 1 ~"Management of the economy", 
                                 import_prob == 2 ~"Wages, incomes and salaries", 
                                 import_prob == 3 ~"Unemployment",
                                 import_prob == 4 ~ "Poverty/ destitution", 
                                 import_prob == 5 ~ "Rates and Taxes", 
                                 import_prob == 6 ~ "Loans/ credit", 
                                 import_prob == 7 ~ "Farming/agriculture",
                                 import_prob == 32 ~ "Agricultural marketing",
                                 import_prob == 8 ~ "Food shortage/famine",
                                 import_prob == 9 ~ "Drought", 
                                 import_prob == 10 ~ "Land",
                                 import_prob == 11 ~ "Transportation",
                                 import_prob == 12 ~ "Communications", 
                                 import_prob == 13 ~ "Infrastructure/ roads",
                                 import_prob == 14 ~ "Education",
                                 import_prob == 15 ~ "Housing",
                                 import_prob == 16 ~ "Electricity",
                                 import_prob == 17 ~ "Water supply",
                                 import_prob == 18 ~ "Orphans/ street children/homeless children",
                                 import_prob == 19 ~ "Services (other)",
                                 import_prob == 20 ~ "Health",
                                 import_prob == 21 ~ "aids",
                                 import_prob == 22 ~ "Sickness/ Disease",
                                 import_prob == 23 ~ "Crime and Security",
                                 import_prob == 24 ~ "Corruption",
                                 import_prob == 25 ~ "Political violence", 
                                 import_prob == 26 ~ "Political instability/ ethnic tensions",
                                 import_prob == 27 ~ "Discrimination/ inequality", 
                                 import_prob == 28 ~ "Gender issues / womens rights",
                                 import_prob == 29 ~ "Democracy/political rights",
                                 import_prob == 31 ~ "Civil war",
                                 import_prob == 30 ~ "International war",
                                  TRUE ~ "NA"))

# creating and saving important issue sentiment data for 2018 

sent_tot_2018 <- sent_tot %>%
  filter(year == "2018") %>%
  subset(select = -year)

saveRDS(sent_tot_2018, file = "shiny/data/sent_tot_2018.rds")

# creating and saving important issue sentiment data for 2013

sent_tot_2013 <- sent_tot %>%
  filter(year == "2013") %>%
  subset(select = -year)

saveRDS(sent_tot_2013, file = "shiny/data/sent_tot_2013.rds")


```




